cmake -S . -B build  -G Ninja \
      -D CMAKE_BUILD_TYPE:STRING="Release" \
      -D CMAKE_FIND_ROOT_PATH="$PREFIX;$BUILD_PREFIX/$HOST/sysroot" \
      -D CMAKE_INSTALL_PREFIX:FILEPATH=$PREFIX \
      -D CMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=TRUE \
      -D CMAKE_PREFIX_PATH:FILEPATH=$PREFIX \
      -D 3RDPARTY_DIR:FILEPATH=$PREFIX \
      -D 3RDPARTY_VTK_INCLUDE_DIR:FILEPATH=$PREFIX/include/vtk-9.6 \
      -D 3RDPARTY_VTK_LIBRARY_DIR:FILEPATH=$PREFIX/lib \
      -D BUILD_MODULE_Draw:BOOL=OFF \
      -D BUILD_RELEASE_DISABLE_EXCEPTIONS:BOOL=OFF \
      -D QT_HOST_PATH:STRING="${PREFIX}" \
      -D USE_FREEIMAGE:BOOL=ON \
      -D USE_RAPIDJSON:BOOL=ON \
      -D USE_TBB:BOOL=OFF \
      -D USE_VTK:BOOL=$USE_VTK \
      -D VTK_RENDERING_BACKEND:STRING="OpenGL2"

cmake --build build -- install
